### ISSUE TITLE
Incorrect results when working with large denominators

### ISSUE THREAD

**Issue by mossadal** [chippyash/Math-Type-Calculator#1]
```
$calc = new Calculator();
$a = RationalTypeFactory::fromFloat(M_PI);
$b = RationalTypeFactory::fromFloat(M_E);
$x = $calc->sub($a,$b);
$y = $calc->add($a,$b);
```

results in `$x = -46786361385/265081044305386` (which evaluates to `-0.1764983291e-3`) instead of the correct `112211675591433/265081044305386` (which is `0.4233108251`).

Similarly `$y = -426104824859/265081044305386` which is even more obviously wrong.

Adding `RequiredType::getInstance()->set(RequiredType::TYPE_NATIVE);` makes no difference.

**Comment by chippyash** [comment]
will take a look

**Comment by chippyash** [comment]
The cause is that IntType, which RationalType uses for numerator and denominator forces an intval as its  value.  The Calculator will only work with Native PHP types at the present time, work on getting a GMP engine is under way.  Consider this:

```
        $a = 80143857;  //numerator for M_PI                
        $b = 265081044305386;  //lcm of M_PI and M_E       

        $aa = RationalTypeFactory::create($a);  
        $bb = RationalTypeFactory::create($b);  

        $expected = $a * $b;  //gives 2.1244617308222E+22 a FLOAT and is > PHP_INT_MAX
        $test = $calc->mul($aa, $bb)->get()  // gives -6031864691884556288 - integer overflow
        $this->assertEquals($expected, $test);  //fails as intval(2.1244617308222E+22) == -6031864691884556288
```

So basically, you blew out PHP's integer capacity with your example :-(

Thanks for the feedback though, I have a good test for the GMP engine.

**Comment by mossadal** [comment]
I figured it was an integer overflow as the cause, but I'm sorry to say that this makes your code almost impossible for general use. Adding sqrt(2) and sort(3) exhibits the same error. Using rationals as the base type (implemented as pair of normal integers), you will quickly run into similar things, since denominators tend to grow exponentially with the number of operations.

I would suggest that you change the implemenation of rational arithmetic so that the results are not exact, but that you instead use a suitable continued fraction for the exact result to keep the numerators and denominators from overflowing.

**Comment by chippyash** [comment]
Hmm, not sure I agree about 'impossible for general use.  StrongType is generally used for 2 things
- to enforce types
- to give some missing types.

This lib is adding functionality for strong types to be used in a more mathematical setting (primarily to support my matrix work, for which they are performing adequately.) As I said before, I'm adding GMP support as I know there are very real limitations using inbuilt integer support.

If you'd like to have a go at adding the functionality you suggest in the meantime, I'd be happy to consider it.  Thanks for your feedback.

**Comment by mossadal** [comment]
I had a look at your matrix library as well, and you may be interested in knowing that

```
$A = new RationalMatrix([
    [ 0.331, 0.579, 0.812, 0.912 ],
    [ 0.173, 0.237, 0.575, 0.053 ],
    [ 0.217, 0.543, 0.871, 0.419 ],
    [ 0.091, 0.431, 0.197, 0.134 ]
]);
$lu = $A('Lu');
```

gives an incorrect result (and it's not really anything special about the numbers in `$A`) for the same reason as above. Multiplying the resulting factors, `L*U` is

```
+----------------------------------------------------------------------------------------+
|              331/1000              579/1000               203/250               114/125|
|               91/1000              431/1000              197/1000                67/500|
|              217/1000              543/1000              871/1000              419/1000|
|              173/1000              237/1000                 23/40 36867/179321584950500|
+----------------------------------------------------------------------------------------+
```

instead of the correct (`P*A`)

```
+------------------------------------+
| 331/1000 579/1000  203/250  114/125|
|  91/1000 431/1000 197/1000   67/500|
| 217/1000 543/1000 871/1000 419/1000|
| 173/1000 237/1000    23/40  53/1000|
+------------------------------------+
```

I like the idea of your lib and it has several interesting ideas, but it looks like I will not use it in the project that I'm working on now.

Therefore I will likely not provide a PR of my suggested reimplementation, but you probably want to think about how to handle this.
